import {
  LayoutDashboard,
  Users,
  Briefcase,
  ShieldCheck,
  ClipboardList,
  Headphones,
  Flag,
  Wallet,
  Bell,
  BarChart3,
  Settings,
  ScrollText,
  Layers,
  Gift,
  FileText,
  Building2,
  Tags,
  AlertTriangle,
  CreditCard,
  TicketCheck,
  Percent,
  ToggleRight,
  type LucideIcon,
} from "lucide-react"

export const ADMIN_ROUTES = {
  LOGIN: "/admin/login",
  DASHBOARD: "/admin/dashboard",
  CLIENTS: "/admin/clients",
  CLIENT_DETAIL: "/admin/clients/:id",
  PROS: "/admin/pros",
  PRO_DETAIL: "/admin/pros/:id",
  VERIFICATIONS: "/admin/verifications",
  MISSIONS: "/admin/missions",
  MISSION_DETAIL: "/admin/missions/:id",
  SUPPORT: "/admin/support",
  SUPPORT_TICKET_DETAIL: "/admin/support/:id",
  REPORTS: "/admin/reports",
  PAYMENTS: "/admin/payments",
  NOTIFICATIONS: "/admin/notifications",
  NOTIFICATION_CREATE: "/admin/notifications/create",
  ANALYTICS: "/admin/analytics",
  SETTINGS: "/admin/settings",
  LOGS: "/admin/logs",
  APPLICATIONS: "/admin/applications",
  APPLICATION_DETAIL: "/admin/applications/:id",
  CATEGORIES: "/admin/categories",
  PROMOTIONS: "/admin/promotions",
  CMS: "/admin/cms",
  ROLES: "/admin/roles",
  FRAUD: "/admin/fraud",
  SUBSCRIPTIONS: "/admin/subscriptions",
  PLANS: "/admin/plans",
  FEATURES: "/admin/features",
  INVOICES: "/admin/invoices",
  COUPONS: "/admin/coupons",
  REVENUE_ANALYTICS: "/admin/analytics/revenue",
  FEATURE_FLAGS: "/admin/feature-flags",
} as const

export interface NavItem {
  label: string
  href: string
  icon: LucideIcon
  permission?: string
  badge?: string
}

export const ADMIN_NAV_ITEMS: NavItem[] = [
  { label: "Dashboard", href: ADMIN_ROUTES.DASHBOARD, icon: LayoutDashboard, permission: "analytics.read" },
  { label: "Clients", href: ADMIN_ROUTES.CLIENTS, icon: Users, permission: "users.read" },
  { label: "Professionnels", href: ADMIN_ROUTES.PROS, icon: Briefcase, permission: "pros.read" },
  { label: "Vérifications", href: ADMIN_ROUTES.VERIFICATIONS, icon: ShieldCheck, permission: "verifications.read" },
  { label: "Candidatures", href: ADMIN_ROUTES.APPLICATIONS, icon: Users, permission: "applications.read" },
  { label: "Missions", href: ADMIN_ROUTES.MISSIONS, icon: ClipboardList, permission: "missions.read" },
  { label: "Paiements", href: ADMIN_ROUTES.PAYMENTS, icon: Wallet, permission: "payments.read" },
  { label: "Support", href: ADMIN_ROUTES.SUPPORT, icon: Headphones, permission: "support.read" },
  { label: "Signalements", href: ADMIN_ROUTES.REPORTS, icon: Flag, permission: "reports.read" },
  { label: "Abonnements", href: ADMIN_ROUTES.SUBSCRIPTIONS, icon: CreditCard, permission: "subscription.read" },
  { label: "Plans", href: ADMIN_ROUTES.PLANS, icon: TicketCheck, permission: "plan.create" },
  { label: "Fonctionnalités", href: ADMIN_ROUTES.FEATURES, icon: Layers, permission: "plan.create" },
  { label: "Feature Flags", href: ADMIN_ROUTES.FEATURE_FLAGS, icon: ToggleRight, permission: "feature_flags.read" },
  { label: "Factures", href: ADMIN_ROUTES.INVOICES, icon: FileText, permission: "subscription.read" },
  { label: "Coupons", href: ADMIN_ROUTES.COUPONS, icon: Percent, permission: "coupon.manage" },
  { label: "Notifications", href: ADMIN_ROUTES.NOTIFICATIONS, icon: Bell, permission: "notifications.read" },
  { label: "Catégories", href: ADMIN_ROUTES.CATEGORIES, icon: Layers, permission: "categories.read" },
  { label: "Promotions", href: ADMIN_ROUTES.PROMOTIONS, icon: Gift, permission: "promotions.read" },
  { label: "CMS", href: ADMIN_ROUTES.CMS, icon: FileText, permission: "cms.read" },
  { label: "Rôles", href: ADMIN_ROUTES.ROLES, icon: Building2, permission: "roles.read" },
  { label: "Fraude", href: ADMIN_ROUTES.FRAUD, icon: AlertTriangle, permission: "fraud.read" },
  { label: "Analytics", href: ADMIN_ROUTES.ANALYTICS, icon: BarChart3, permission: "analytics.read" },
  { label: "Revenus", href: ADMIN_ROUTES.REVENUE_ANALYTICS, icon: BarChart3, permission: "analytics.read" },
  { label: "Paramètres", href: ADMIN_ROUTES.SETTINGS, icon: Settings, permission: "settings.read" },
  { label: "Logs", href: ADMIN_ROUTES.LOGS, icon: ScrollText, permission: "logs.read" },
]
