import { PrismaClient } from "@prisma/client";

const prisma = new PrismaClient();

async function main() {
  // ── 1. Seed categories (idempotent) ──
  const categories = [
    { name: "Plombier", slug: "plombier", icon: "Wrench", order: 1 },
    { name: "Électricien", slug: "electricien", icon: "Lightbulb", order: 2 },
    { name: "Menuisier", slug: "menuisier", icon: "Sofa", order: 3 },
    { name: "Réparateur", slug: "reparateur", icon: "Smartphone", order: 4 },
    { name: "Ménager", slug: "menager", icon: "Sparkles", order: 5 },
    { name: "Cours & Coaching", slug: "cours-coaching", icon: "BookOpen", order: 6 },
    { name: "Climatisation", slug: "climatisation", icon: "Wind", order: 7 },
    { name: "Coiffure & Beauté", slug: "coiffure-beaute", icon: "Scissors", order: 8 },
  ];

  for (const cat of categories) {
    await prisma.category.upsert({
      where: { slug: cat.slug },
      update: { name: cat.name, icon: cat.icon, order: cat.order },
      create: cat,
    });
  }
  console.log("✅ Categories seeded");

  // ── 2. Clear old pro/ client data ──
  await prisma.review.deleteMany();
  await prisma.portfolioItem.deleteMany();
  await prisma.message.deleteMany();
  await prisma.pricing.deleteMany();
  await prisma.service.deleteMany();
  await prisma.mission.deleteMany();
  await prisma.profile.deleteMany();
  await prisma.session.deleteMany();
  await prisma.user.deleteMany();
  console.log("🧹 Old data cleared");

  // ── 3. Demo client (for reviews / missions) ──
  const client = await prisma.user.create({
    data: {
      phone: "+2250101020304",
      role: "CLIENT",
      status: "ACTIVE",
      profile: {
        create: {
          firstName: "Ahou",
          lastName: "Mireille",
          profession: "Cliente",
          bio: "Client Ça Match",
          zone: ["Cocody", "Marcory"],
          trustScore: 100,
          badge: "NONE",
        },
      },
    },
  });
  console.log("✅ Demo client created");

  // ── 4. 20 fake pros ──
  const pros = [
    // ── Plombier ──
    {
      phone: "+2250102030501",
      firstName: "Kouamé",
      lastName: "Yao",
      profession: "Plombier",
      bio: "Plombier professionnel avec 15 ans d'expérience. Installation, dépannage et entretien de tous types de canalisations. Intervention rapide dans tout Abidjan.",
      zone: ["Cocody", "Marcory", "Plateau"],
      trustScore: 92,
      badge: "GOLD" as const,
      isVerified: true,
      isOnsiteVerified: true,
      experience: 15,
      missionCount: 340,
      responseTime: 15,
      acceptanceRate: 97,
      category: "Plombier",
      services: ["Dépannage urgence", "Installation robinetterie", "Détartrage chauffe-eau"],
      pricing: [
        { label: "Dépannage standard", price: 15000, isStartingAt: false },
        { label: "Installation robinet", price: 25000, isStartingAt: true },
      ],
    },
    {
      phone: "+2250102030502",
      firstName: "Amoin",
      lastName: "N'Guessan",
      profession: "Plombière",
      bio: "Plombière agréée spécialisée dans les installations modernes. Je réalise vos projets de rénovation sanitaire avec soin et professionnalisme.",
      zone: ["Marcory", "Treichville", "Koumassi"],
      trustScore: 78,
      badge: "SILVER" as const,
      isVerified: true,
      isOnsiteVerified: false,
      experience: 8,
      missionCount: 185,
      responseTime: 25,
      acceptanceRate: 88,
      category: "Plombier",
      services: ["Rénovation salle de bain", "Installation chauffe-eau", "Détection fuite"],
      pricing: [
        { label: "Détection fuite", price: 20000, isStartingAt: false },
        { label: "Rénovation salle de bain", price: 150000, isStartingAt: true },
      ],
    },
    {
      phone: "+2250102030503",
      firstName: "Koné",
      lastName: "Moussa",
      profession: "Plombier",
      bio: "Maître plombier avec plus de 20 ans d'expérience. Je intervenir sur tout type de chantier, du simple robinet à la plomberie industrielle.",
      zone: ["Yopougon", "Abobo", "Adjamé"],
      trustScore: 95,
      badge: "GOLD" as const,
      isVerified: true,
      isOnsiteVerified: true,
      experience: 22,
      missionCount: 520,
      responseTime: 10,
      acceptanceRate: 99,
      category: "Plombier",
      services: ["Plomberie générale", "Pompe à eau", "Curage canalisation"],
      pricing: [
        { label: "Intervention simple", price: 12000, isStartingAt: true },
        { label: "Curage canalisation", price: 35000, isStartingAt: false },
      ],
    },
    // ── Électricien ──
    {
      phone: "+2250102030504",
      firstName: "N'Dri",
      lastName: "Akissi",
      profession: "Électricienne",
      bio: "Électricienne agréée. Spécialiste en installation électrique domestique et industrielle. Sécurité et conformité sont mes maîtres mots.",
      zone: ["Plateau", "Cocody", "Marcory"],
      trustScore: 88,
      badge: "SILVER" as const,
      isVerified: true,
      isOnsiteVerified: true,
      experience: 12,
      missionCount: 280,
      responseTime: 20,
      acceptanceRate: 93,
      category: "Électricien",
      services: ["Installation électrique", "Dépannage", "Tableau électrique"],
      pricing: [
        { label: "Dépannage", price: 15000, isStartingAt: true },
        { label: "Installation complète", price: 75000, isStartingAt: false },
      ],
    },
    {
      phone: "+2250102030505",
      firstName: "Bamba",
      lastName: "Souleymane",
      profession: "Électricien",
      bio: "Jeune électricien dynamique spécialisé dans le dépannage rapide et l'installation domestique. Interventions soignées à prix abordables.",
      zone: ["Treichville", "Port-Bouët", "Koumassi"],
      trustScore: 72,
      badge: "BRONZE" as const,
      isVerified: false,
      isOnsiteVerified: false,
      experience: 6,
      missionCount: 120,
      responseTime: 30,
      acceptanceRate: 85,
      category: "Électricien",
      services: ["Dépannage express", "Montage prises", "Éclairage"],
      pricing: [
        { label: "Dépannage express", price: 10000, isStartingAt: true },
        { label: "Installation prise", price: 5000, isStartingAt: false },
      ],
    },
    {
      phone: "+2250102030506",
      firstName: "Koffi",
      lastName: "Lazare",
      profession: "Électricien",
      bio: "Ingénieur électricien de formation, je réalise tous vos projets électriques avec précision. Certification NFC et garantie décennale.",
      zone: ["Cocody", "Plateau", "Bingerville"],
      trustScore: 96,
      badge: "ELITE" as const,
      isVerified: true,
      isOnsiteVerified: true,
      experience: 18,
      missionCount: 450,
      responseTime: 5,
      acceptanceRate: 98,
      category: "Électricien",
      services: ["Installation complète", "Domotique", "Mise aux normes"],
      pricing: [
        { label: "Mise aux normes", price: 50000, isStartingAt: false },
        { label: "Installation domotique", price: 200000, isStartingAt: true },
      ],
    },
    // ── Menuisier ──
    {
      phone: "+2250102030507",
      firstName: "Diallo",
      lastName: "Ousmane",
      profession: "Menuisier",
      bio: "Menuisier ébéniste depuis 20 ans. Meubles sur mesure, cuisine équipée, agencement intérieur. Artisanat de qualité et finitions soignées.",
      zone: ["Abobo", "Yopougon", "Adjamé"],
      trustScore: 85,
      badge: "SILVER" as const,
      isVerified: true,
      isOnsiteVerified: false,
      experience: 20,
      missionCount: 310,
      responseTime: 20,
      acceptanceRate: 91,
      category: "Menuisier",
      services: ["Meubles sur mesure", "Cuisine équipée", "Agencement"],
      pricing: [
        { label: "Petite réparation", price: 10000, isStartingAt: true },
        { label: "Meuble sur mesure", price: 80000, isStartingAt: false },
      ],
    },
    {
      phone: "+2250102030508",
      firstName: "Tano",
      lastName: "Béatrice",
      profession: "Menuisière",
      bio: "Menuisière décoratrice. Passionnée par le travail du bois, je crée des pièces uniques pour votre intérieur. Approche artisanale et moderne.",
      zone: ["Bingerville", "Cocody", "Marcory"],
      trustScore: 90,
      badge: "GOLD" as const,
      isVerified: true,
      isOnsiteVerified: true,
      experience: 10,
      missionCount: 160,
      responseTime: 15,
      acceptanceRate: 95,
      category: "Menuisier",
      services: ["Mobilier design", "Décoration bois", "Rénovation"],
      pricing: [
        { label: "Table design", price: 120000, isStartingAt: false },
        { label: "Consultation décoration", price: 25000, isStartingAt: true },
      ],
    },
    // ── Réparateur ──
    {
      phone: "+2250102030509",
      firstName: "Ouattara",
      lastName: "Adama",
      profession: "Réparateur téléphone",
      bio: "Spécialiste en réparation de téléphones et tablettes. Remplacement écran, batterie, connectique. Pièces d'origine et garantie 6 mois.",
      zone: ["Adjamé", "Treichville", "Plateau"],
      trustScore: 76,
      badge: "SILVER" as const,
      isVerified: true,
      isOnsiteVerified: false,
      experience: 7,
      missionCount: 890,
      responseTime: 10,
      acceptanceRate: 96,
      category: "Réparateur",
      services: ["Remplacement écran", "Changement batterie", "Réparation logicielle"],
      pricing: [
        { label: "Remplacement écran", price: 25000, isStartingAt: false },
        { label: "Diagnostic", price: 5000, isStartingAt: true },
      ],
    },
    {
      phone: "+2250102030510",
      firstName: "Yao",
      lastName: "Estelle",
      profession: "Réparatrice smartphone",
      bio: "Réparatrice agréée Apple et Samsung. Passionnée de tech, je redonne vie à vos appareils avec des pièces de haute qualité.",
      zone: ["Marcory", "Cocody"],
      trustScore: 81,
      badge: "SILVER" as const,
      isVerified: true,
      isOnsiteVerified: false,
      experience: 5,
      missionCount: 560,
      responseTime: 15,
      acceptanceRate: 94,
      category: "Réparateur",
      services: ["Réparation iPhone", "Réparation Samsung", "Dépannage PC"],
      pricing: [
        { label: "Réparation iPhone écran", price: 35000, isStartingAt: false },
        { label: "Nettoyage logiciel", price: 7000, isStartingAt: true },
      ],
    },
    {
      phone: "+2250102030511",
      firstName: "Kraidy",
      lastName: "André",
      profession: "Réparateur électroménager",
      bio: "Technicien en électroménager. Je répare tous vos appareils: lave-linge, frigo, micro-ondes, cuisinière. Plus de 14 ans d'expérience.",
      zone: ["Yopougon", "Abobo", "Koumassi"],
      trustScore: 70,
      badge: "BRONZE" as const,
      isVerified: false,
      isOnsiteVerified: false,
      experience: 14,
      missionCount: 420,
      responseTime: 25,
      acceptanceRate: 82,
      category: "Réparateur",
      services: ["Réparation lave-linge", "Réparation frigo", "Entretien clim"],
      pricing: [
        { label: "Diagnostic", price: 8000, isStartingAt: true },
        { label: "Réparation lave-linge", price: 20000, isStartingAt: false },
      ],
    },
    // ── Ménager ──
    {
      phone: "+2250102030512",
      firstName: "Konan",
      lastName: "Martine",
      profession: "Femme de ménage",
      bio: "Service de nettoyage professionnel pour particuliers et entreprises. Produits écologiques, matériel moderne, équipe ponctuelle.",
      zone: ["Cocody", "Marcory", "Plateau"],
      trustScore: 88,
      badge: "SILVER" as const,
      isVerified: true,
      isOnsiteVerified: true,
      experience: 6,
      missionCount: 230,
      responseTime: 30,
      acceptanceRate: 98,
      category: "Ménager",
      services: ["Nettoyage complet", "Nettoyage bureau", "Repassage"],
      pricing: [
        { label: "Nettoyage appartement", price: 15000, isStartingAt: true },
        { label: "Nettoyage bureau", price: 25000, isStartingAt: false },
      ],
    },
    {
      phone: "+2250102030513",
      firstName: "Zadi",
      lastName: "Fanta",
      profession: "Agent d'entretien",
      bio: "Service d'entretien ménager de qualité. Grande expérience dans le nettoyage de bureaux, villas et appartements. Références fournies.",
      zone: ["Plateau", "Treichville", "Adjamé"],
      trustScore: 74,
      badge: "BRONZE" as const,
      isVerified: false,
      isOnsiteVerified: false,
      experience: 4,
      missionCount: 140,
      responseTime: 40,
      acceptanceRate: 90,
      category: "Ménager",
      services: ["Ménage standard", "Grand nettoyage", "Nettoyage vitres"],
      pricing: [
        { label: "Ménage standard 2h", price: 10000, isStartingAt: true },
        { label: "Nettoyage vitres", price: 15000, isStartingAt: false },
      ],
    },
    // ── Cours & Coaching ──
    {
      phone: "+2250102030514",
      firstName: "Boni",
      lastName: "Gérald",
      profession: "Professeur d'anglais",
      bio: "Professeur d'anglais certifié TOEFL. Cours pour tous niveaux: scolaire, professionnel, conversation. Méthode interactive et résultats garantis.",
      zone: ["Cocody", "Marcory", "Plateau"],
      trustScore: 91,
      badge: "GOLD" as const,
      isVerified: true,
      isOnsiteVerified: true,
      experience: 9,
      missionCount: 380,
      responseTime: 5,
      acceptanceRate: 96,
      category: "Cours & Coaching",
      services: ["Cours d'anglais", "Préparation TOEFL", "Anglais professionnel"],
      pricing: [
        { label: "Cours particulier 1h", price: 8000, isStartingAt: true },
        { label: "Forfait 10 séances", price: 70000, isStartingAt: false },
      ],
    },
    {
      phone: "+2250102030515",
      firstName: "Kouakou",
      lastName: "Armande",
      profession: "Coach sportif",
      bio: "Coach sportif diplômée. Programmes personnalisés en musculation, cardio et perte de poids. Suivi en ligne et en présentiel.",
      zone: ["Marcory", "Cocody", "Bingerville"],
      trustScore: 84,
      badge: "SILVER" as const,
      isVerified: true,
      isOnsiteVerified: false,
      experience: 5,
      missionCount: 190,
      responseTime: 15,
      acceptanceRate: 92,
      category: "Cours & Coaching",
      services: ["Coaching personnel", "Programme perte poids", "Yoga"],
      pricing: [
        { label: "Séance individuelle", price: 12000, isStartingAt: true },
        { label: "Forfait mensuel", price: 80000, isStartingAt: false },
      ],
    },
    {
      phone: "+2250102030516",
      firstName: "Timité",
      lastName: "Ibrahim",
      profession: "Professeur de maths",
      bio: "Professeur de mathématiques et sciences. J'accompagne les élèves du collège au lycée avec une pédagogie adaptée à chacun.",
      zone: ["Abobo", "Yopougon", "Adjamé"],
      trustScore: 79,
      badge: "BRONZE" as const,
      isVerified: false,
      isOnsiteVerified: false,
      experience: 11,
      missionCount: 270,
      responseTime: 20,
      acceptanceRate: 89,
      category: "Cours & Coaching",
      services: ["Mathématiques", "Physique-chimie", "Soutien scolaire"],
      pricing: [
        { label: "Cours 1h", price: 6000, isStartingAt: true },
        { label: "Forfait trimestre", price: 50000, isStartingAt: false },
      ],
    },
    // ── Climatisation ──
    {
      phone: "+2250102030517",
      firstName: "Kassi",
      lastName: "Emile",
      profession: "Climaticien",
      bio: "Expert en climatisation. Installation, entretien et dépannage de tous types de clims. Agréé par les principales marques. Intervention 7j/7.",
      zone: ["Treichville", "Cocody", "Plateau", "Marcory"],
      trustScore: 93,
      badge: "GOLD" as const,
      isVerified: true,
      isOnsiteVerified: true,
      experience: 16,
      missionCount: 650,
      responseTime: 5,
      acceptanceRate: 97,
      category: "Climatisation",
      services: ["Installation clim", "Dépannage", "Entretien annuel"],
      pricing: [
        { label: "Entretien clim", price: 15000, isStartingAt: true },
        { label: "Installation split", price: 85000, isStartingAt: false },
      ],
    },
    {
      phone: "+2250102030518",
      firstName: "Touré",
      lastName: "Mamadou",
      profession: "Installateur clim",
      bio: "Installateur de systèmes de climatisation et ventilation. Devis gratuit, travail soigné et garantie sur toutes mes interventions.",
      zone: ["Koumassi", "Port-Bouët", "Yopougon"],
      trustScore: 77,
      badge: "SILVER" as const,
      isVerified: true,
      isOnsiteVerified: false,
      experience: 8,
      missionCount: 190,
      responseTime: 20,
      acceptanceRate: 90,
      category: "Climatisation",
      services: ["Installation clim", "Dépannage", "Ventilation"],
      pricing: [
        { label: "Nettoyage clim", price: 10000, isStartingAt: true },
        { label: "Dépannage urgence", price: 25000, isStartingAt: false },
      ],
    },
    // ── Coiffure & Beauté ──
    {
      phone: "+2250102030519",
      firstName: "Koffi",
      lastName: "Awa",
      profession: "Coiffeuse",
      bio: "Coiffeuse professionnelle spécialisée dans les tresses, tissages et coupes modernes. Salon climatisé à Cocody. Produits de qualité.",
      zone: ["Cocody", "Marcory"],
      trustScore: 87,
      badge: "SILVER" as const,
      isVerified: true,
      isOnsiteVerified: true,
      experience: 7,
      missionCount: 420,
      responseTime: 10,
      acceptanceRate: 95,
      category: "Coiffure & Beauté",
      services: ["Tresses", "Tissage", "Coupe et brushing"],
      pricing: [
        { label: "Coupe + brushing", price: 10000, isStartingAt: true },
        { label: "Tissage complet", price: 35000, isStartingAt: false },
      ],
    },
    {
      phone: "+2250102030520",
      firstName: "Mambo",
      lastName: "Chloé",
      profession: "Coiffeuse",
      bio: "Coiffeuse passionnée, je vous conseille et réalise la coiffure qui vous mettra en valeur. Pose de mèches, coloration et soins.",
      zone: ["Marcory", "Treichville", "Adjamé"],
      trustScore: 69,
      badge: "BRONZE" as const,
      isVerified: false,
      isOnsiteVerified: false,
      experience: 3,
      missionCount: 95,
      responseTime: 30,
      acceptanceRate: 86,
      category: "Coiffure & Beauté",
      services: ["Coloration", "Mèches", "Soins capillaires"],
      pricing: [
        { label: "Brushing", price: 5000, isStartingAt: true },
        { label: "Coloration", price: 20000, isStartingAt: false },
      ],
    },
  ];

  // ── 5. Create each pro ──
  for (const p of pros) {
    const user = await prisma.user.create({
      data: {
        phone: p.phone,
        role: "PROFESSIONAL",
        status: "ACTIVE",
        profile: {
          create: {
            firstName: p.firstName,
            lastName: p.lastName,
            profession: p.profession,
            bio: p.bio,
            zone: p.zone,
            trustScore: p.trustScore,
            badge: p.badge,
            isVerified: p.isVerified,
            isOnsiteVerified: p.isOnsiteVerified,
            experience: p.experience,
            missionCount: p.missionCount,
            responseTime: p.responseTime,
            acceptanceRate: p.acceptanceRate,
            availability: { weekdays: true, weekends: false },
            services: {
              create: p.services.map((name) => ({
                name,
                category: p.category,
              })),
            },
            pricing: {
              create: p.pricing.map((pr) => ({
                service: pr.label,
                label: pr.label,
                price: pr.price,
                isStartingAt: pr.isStartingAt,
              })),
            },
          },
        },
      },
    });
    console.log(`  ✅ ${p.firstName} ${p.lastName} — ${p.profession} (${p.trustScore} pts, ${p.badge})`);
  }

  console.log("🎉 20 pros créés avec succès !");
}

main()
  .catch((e) => {
    console.error(e);
    process.exit(1);
  })
  .finally(() => prisma.$disconnect());
